### ISSUE TITLE
AutoBuy double buys

### ISSUE THREAD

**Issue by ahakola** [ahakola/DMFQuest#5]
Sometimes at least with tailoring the AutoBuy buys the mats more than once. This can probably happen with any profession if it can happen with one.

Reported by David with PM in Curseforge.

**Comment by dblanch369** [comment]
Attaching the screenshots here, as I don't think they went in the CF PM....

Thanks Ahak. I totally forgot about the issues posted here.  The "Issues" button on the CF page took me to the outdated issues page. heh

Here are the screenys


![Screenshot 2024-04-07 at 9 54 04 PM](https://github.com/ahakola/DMFQuest/assets/23128709/2d2cea62-b784-4528-9c5d-7e0a8652e7c3)
![Screenshot 2024-04-07 at 9 54 37 PM](https://github.com/ahakola/DMFQuest/assets/23128709/0a07a5eb-8d73-47bb-825e-5356837e57d7)

**Comment by ahakola** [comment]
> The "Issues" button on the CF page took me to the outdated issues page.

Ye, the CF is in some kind of weird limbo where some of the stuff is available only in the legacy site but they push the modern site to the users. I personally prefer Github for these tickets, but not everyone on CurseForge have Github account, so I have to look for issue reports on Github, CF Issues page for this addon and also from comments for the addon, because that seems to be the go to place to report stuff for some people.

I believe the issue is appears when the AutoBuy has to buy more than just a few items. On some of the characters I tested, I couldn't run into the issue, but as soon as I tried with character who has tailoring (3 items + 1 for cooking) the double buy happened every time.

I just pushed out new version 3.0.2 that should fix this issue, but don't hesitate to reopen this ticket if the issue still persists.

**Comment by dblanch369** [comment]
I’m curious, did you have to add a delay or something to ensure the server responded to the purchase? Or was it something else?DavidOn Apr 10, 2024, at 12:11 PM, ahakola ***@***.***> wrote:﻿

The "Issues" button on the CF page took me to the outdated issues page.

Ye, the CF is in some kind of wierd limbo where some of the stuff is available only in the legacy site but they push the modern site to the users. I personally prefer Github for these tickets, but not everyone on CurseForge have Github account, so I have to look for issue reports on Github, CF Issues page for this addon and also from comments for the addon, because that seems to be the go to place to report stuff for some people.
I believe the issue is appears when the AutoBuy has to buy more than just a few items. On some of the characters I tested, I couldn't run into the issue, but as soon as I tried with character who has tailoring (3 items + 1 for cooking) the double buy happened every time.
I just pushed out new version 3.0.2 that should fix this issue, but don't hesitate to reopen this ticket if the issue still persists.

**Comment by ahakola** [comment]
I added a check before calling the actual buying function where I compare current time to the last time the buying was completed and if it is under 2 seconds, don't call the buy function. I first tested on 1 second, but on PTR at least for me it was about 1/3 of a second too fast. Maybe it would have worked on live with player and realm being from same region.
